#!/bin/bash
cd /home/ec2-user/vital
export NODE_ENV=prod
export GOOGLE_APPLICATION_CREDENTIALS=/home/ec2-user/firebase_node_creds.json
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
npm run serve